<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Andy.Rbac.Client</PackageId>
    <Description>HTTP and gRPC client for Andy RBAC API. Use this package in applications that need to check permissions against the centralized RBAC service.</Description>
    <PackageTags>rbac;authorization;client;grpc</PackageTags>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Andy.Rbac\Andy.Rbac.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Andy.Auth.M2MClient" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\..\proto\rbac.proto" GrpcServices="Client" Link="Protos\rbac.proto" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\..\assets\andy_rbac_icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
